spin_version = "1"
authors = ["karthik Ganeshram <karthik.ganeshram@fermyon.com>"]
description = ""
name = "spin-kv"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-kv"
source = "target/spin-http-js.wasm"
exclude_files = ["**/node_modules"]
key_value_stores = ["default"]
[component.trigger]
route = "/..."
[component.build]
command = "npm run build"
